# Generated by Django 4.2.6 on 2023-11-03 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("form_data", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "IDLE"),
                            ("READY", "READY"),
                            ("COLLECTING", "COLLECTING"),
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="IDLE",
                        max_length=128,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "flow_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("flow_scope", models.CharField(max_length=128)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlowAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorization_type",
                    models.CharField(
                        choices=[
                            ("USER", "USER"),
                            ("CONFIDENTIAL_CLIENT", "CONFIDENTIAL_CLIENT"),
                            ("CONFIDENTIAL_TOKEN", "CONFIDENTIAL_TOKEN"),
                        ],
                        default="USER",
                        max_length=128,
                    ),
                ),
                (
                    "authorization_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("authorization_cache", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(blank=True, max_length=128, null=True)),
                ("label", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "IDLE"),
                            ("READY", "READY"),
                            ("STARTED", "STARTED"),
                            ("ACTIVE", "ACTIVE"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="IDLE",
                        max_length=128,
                    ),
                ),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("start_kwargs_data", models.TextField(blank=True, null=True)),
                ("payload", models.TextField(blank=True, null=True)),
                ("error_data", models.TextField(blank=True, null=True)),
                (
                    "authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globus_app_flows.flowauthorization",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globus_app_flows.batch",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globus_app_flows.flow",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collector_type", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "IDLE"),
                            ("READY", "READY"),
                            ("ACTIVE", "ACTIVE"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="IDLE",
                        max_length=128,
                    ),
                ),
                ("collector_data", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batch",
            name="authorization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="globus_app_flows.flowauthorization",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="collector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="globus_app_flows.collector",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="globus_app_flows.flow"
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
